Repository tonightpass/kitchn, pull requests merged in 2022-12, with the labels that each got.

#62 ✨ add local fonts
  examples/next-typescript/pages/_app.tsx
  examples/next-typescript/pages/_document.tsx
  packages/kitchen/fonts.css
  packages/kitchen/package.json
  packages/kitchen/src/themes/main.ts
  yarn.lock
Labels: enhancement

#63 ✨ add default light theme
  examples/next-typescript/pages/index.tsx
  packages/kitchen/src/components/Badge/index.tsx
  packages/kitchen/src/components/Button/index.tsx
  packages/kitchen/src/components/GlobalStyle/index.ts
  packages/kitchen/src/components/Note/index.tsx
  packages/kitchen/src/components/Provider/index.tsx
  packages/kitchen/src/contexts/Theme.tsx
  packages/kitchen/src/hooks/useLocalStorage.ts
  packages/kitchen/src/hooks/useTheme.ts
  packages/kitchen/src/hooks/useThemeDetector.tsx
  packages/kitchen/src/index.ts
  packages/kitchen/src/themes/dark.ts
  packages/kitchen/src/themes/index.ts
  packages/kitchen/src/themes/light.ts
Labels: enhancement

#55 ✨ add docs
  .eslintrc.json
  .prettierignore
  docs/.gitignore
  docs/components/GlobalStyle.ts
  docs/components/Playground/code-theme.ts
  docs/components/Playground/dynamic-live.tsx
  docs/components/Playground/editor.tsx
  docs/components/Playground/index.ts
  docs/components/Playground/playground.tsx
  docs/components/Playground/scope.ts
  docs/next-env.d.ts
  docs/next.config.js
  docs/package.json
  docs/pages/_app.tsx
  docs/pages/_document.tsx
  docs/pages/_meta.json
  docs/pages/docs/_meta.json
  docs/pages/docs/components/_meta.json
  docs/pages/docs/components/badge.mdx
  docs/pages/docs/components/button.mdx
  docs/pages/docs/components/grid.mdx
  docs/pages/docs/components/text.mdx
  docs/pages/docs/frameworks/_meta.json
  docs/pages/docs/frameworks/create-react-app.mdx
  docs/pages/docs/frameworks/nextjs.mdx
  docs/pages/docs/guides/_meta.json
  docs/pages/docs/guides/colors.mdx
  docs/pages/docs/guides/icons.mdx
  docs/pages/docs/guides/playground.mdx
  docs/pages/docs/guides/principles.mdx
  docs/pages/docs/guides/theme-builder.mdx
  docs/pages/docs/index.mdx
  docs/pages/index.mdx
  docs/pages/showcase.mdx
  docs/theme.config.tsx
  docs/tsconfig.json
  examples/next-typescript/package.json
  package.json
  packages/kitchen/fonts.css
  packages/kitchen/package.json
  packages/kitchen/src/components/Button/index.tsx
  packages/kitchen/src/components/GlobalStyle/index.ts
  packages/kitchen/src/constants/index.ts
  packages/kitchen/src/contexts/Theme.tsx
  packages/kitchen/src/index.ts
  packages/kitchen/src/themes/main.ts
  packages/kitchen/src/utils/isNumber.ts
  yarn.lock
Labels: documentation, enhancement

#77 🎨 improve husky
  .husky/scripts/validate-branch-name.sh
  .husky/scripts/validate-commit-message.sh
Labels: enhancement

#78 fix editor colors
  docs/components/Playground/code-theme.ts
Labels: enhancement

#76 ✨ add clipboard hook
  docs/components/Playground/editor.tsx
  packages/kitchen/src/constants/index.ts
  packages/kitchen/src/hooks/useClipboard.ts
  packages/kitchen/src/hooks/useLocalStorage.ts
  packages/kitchen/src/hooks/usePortal.tsx
  packages/kitchen/src/hooks/useSSR.ts
  packages/kitchen/src/hooks/useWarning.ts
  packages/kitchen/src/index.ts
  packages/kitchen/src/utils/generateId.ts
  packages/kitchen/src/utils/isBrowser.ts
Labels: enhancement

#80 📝 improve button documentation
  docs/pages/docs/components/button.mdx
Labels: documentation, enhancement

#83 ✨ add logo
  docs/pages/index.mdx
  docs/public/android-chrome-192x192.png
  docs/public/android-chrome-512x512.png
  docs/public/apple-touch-icon.png
  docs/public/favicon-16x16.png
  docs/public/favicon-32x32.png
  docs/public/favicon.ico
  docs/public/manifest.json
  docs/theme.config.tsx
Labels: enhancement

#84 ✨ add turborepo
  .changeset/config.json
  .gitignore
  .husky/scripts/validate-commit-message.sh
  docs/package.json
  examples/expo-typescript/package.json
  examples/next-typescript/package.json
  package.json
  packages/kitchen/package.json
  turbo.json
  yarn.lock
Labels: enhancement

#46 ✨ add checkbox
  .husky/scripts/validate-commit-message.sh
  examples/next-typescript/pages/checkbox.tsx
  examples/next-typescript/pages/index.tsx
  packages/kitchen/package.json
  packages/kitchen/src/components/Checkbox/index.tsx
  packages/kitchen/src/hooks/useCheckbox.ts
  packages/kitchen/src/hooks/useClipboard.ts
  packages/kitchen/src/hooks/usePortal.ts
  packages/kitchen/src/hooks/useThemeDetector.ts
  packages/kitchen/src/index.ts
  yarn.lock
Labels: enhancement

#51 ✨ add link
  examples/next-typescript/pages/index.tsx
  examples/next-typescript/pages/link.tsx
  packages/kitchen/src/components/FragmentLink/index.tsx
  packages/kitchen/src/components/Link/index.tsx
  packages/kitchen/src/index.ts
Labels: enhancement

#86 ✨ add drawer
  examples/next-typescript/pages/drawer.tsx
  examples/next-typescript/pages/index.tsx
  packages/kitchen/src/components/Drawer/index.tsx
  packages/kitchen/src/hooks/useKeyboard.ts
  packages/kitchen/src/index.ts
  packages/kitchen/src/utils/codes.ts
  packages/kitchen/src/utils/getActiveModMap.ts
  packages/kitchen/src/utils/getCtrlKeysByPlatform.ts
  packages/kitchen/src/utils/isMac.ts
Labels: enhancement

#87 ✨ add modal
  .husky/scripts/validate-commit-message.sh
  examples/next-typescript/package.json
  examples/next-typescript/pages/index.tsx
  examples/next-typescript/pages/modal.tsx
  package.json
  packages/kitchen/src/components/Drawer/index.tsx
  packages/kitchen/src/components/Modal/index.tsx
  packages/kitchen/src/hooks/useBreakpoint.ts
  packages/kitchen/src/hooks/useMediaQuery.ts
  packages/kitchen/src/hooks/useModal.ts
  packages/kitchen/src/index.ts
Labels: enhancement

#112 📝 add modal documentation
  docs/pages/docs/components/modal.mdx
Labels: documentation

#111 📝 add notes documentation
  docs/pages/docs/components/note.mdx
Labels: documentation

#103 ✨ add toasts
  examples/next-typescript/pages/index.tsx
  examples/next-typescript/pages/toast.tsx
  packages/kitchen/src/components/Container/index.tsx
  packages/kitchen/src/components/Link/index.tsx
  packages/kitchen/src/components/Provider/index.tsx
  packages/kitchen/src/components/Toast/Actions/index.tsx
  packages/kitchen/src/components/Toast/Container/index.tsx
  packages/kitchen/src/components/Toast/Item/index.tsx
  packages/kitchen/src/contexts/Toasts.tsx
  packages/kitchen/src/hooks/useCurrentState.ts
  packages/kitchen/src/hooks/usePortal.ts
  packages/kitchen/src/hooks/useToasts.ts
  packages/kitchen/src/index.ts
  packages/kitchen/src/themes/main.ts
  packages/kitchen/src/types/theme.ts
  packages/kitchen/src/utils/getId.ts
  packages/kitchen/src/utils/getTranslateByPlacement.ts
Labels: enhancement
