Repository tonightpass/kitchn, pull requests merged in 2023-02, with the labels that each got.

#137 ✨ add landing and scales
  .changeset/large-candles-fry.md
  .changeset/pre.json
  .changeset/silly-bottles-shave.md
  .gitignore
  docs/components/Landing/Featured/index.tsx
  docs/components/Landing/Features/index.tsx
  docs/components/Landing/Render/index.tsx
  docs/components/Landing/Showcase/List/Card/index.tsx
  docs/components/Landing/Showcase/List/index.tsx
  docs/components/Landing/Showcase/index.tsx
  docs/components/Playground/editor.tsx
  docs/data/showcases.ts
  docs/package.json
  docs/pages/_document.tsx
  docs/pages/index.mdx
  docs/public/static/images/showcases/thumbnails/onruntime.svg
  docs/public/static/images/showcases/thumbnails/tonightpass.svg
  docs/screens/Landing/index.tsx
  docs/theme.config.tsx
  docs/types/showcase.ts
  examples/expo-typescript/package.json
  examples/next-typescript/package.json
  package.json
  packages/kitchen/fonts.css
  packages/kitchen/package.json
  packages/kitchen/src/components/Container/index.tsx
  packages/kitchen/src/components/Image/index.tsx
  packages/kitchen/src/components/Text/index.tsx
  packages/kitchen/src/hoc/withScale.tsx
  packages/kitchen/src/index.ts
  packages/kitchen/src/themes/main.ts
  pnpm-lock.yaml
Labels: documentation, enhancement

#146 📝 add create react app example
  .changeset/hip-mugs-try.md
  docs/components/Landing/Featured/index.tsx
  docs/components/Landing/Features/index.tsx
  docs/components/Landing/Render/index.tsx
  docs/components/Landing/Showcase/List/index.tsx
  examples/next-typescript/pages/link.tsx
  examples/react-typescript/package.json
  examples/react-typescript/public/favicon.ico
  examples/react-typescript/public/index.html
  examples/react-typescript/public/logo192.png
  examples/react-typescript/public/logo512.png
  examples/react-typescript/public/manifest.json
  examples/react-typescript/public/robots.txt
  examples/react-typescript/src/App.tsx
  examples/react-typescript/src/index.tsx
  examples/react-typescript/src/react-app-env.d.ts
  examples/react-typescript/tsconfig.json
  package.json
  packages/kitchen/src/components/Error/index.tsx
  packages/kitchen/src/index.ts
  packages/kitchen/src/next/components/Link/Fragment/index.tsx
  packages/kitchen/src/next/components/Link/index.tsx
  packages/kitchen/src/next/index.ts
  pnpm-lock.yaml
Labels: documentation, enhancement

#148 📝 improve react example with kitchen fonts
  examples/react-typescript/src/App.tsx
Labels: enhancement

#127 ✨ add spacer
  .changeset/rotten-poems-pull.md
  examples/next-typescript/pages/index.tsx
  examples/next-typescript/pages/spacer.tsx
  packages/kitchen/src/components/Spacer/index.tsx
  packages/kitchen/src/index.ts
Labels: enhancement

#165 💬 update landing title and subtitle
  docs/components/Landing/Featured/index.tsx
Labels: enhancement, good first issue
